/*  AGPLv3.0 License
* 
* Hypercalc
* 
* Copyright (c) 2017 Simon Y. Blackwell, AnyWhichWay, LLC
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
* 
* You can be released from the requirements of the license by purchasing
* a commercial license. Buying such a license is mandatory as soon as you
* develop commercial activities involving the Hypercalc software without
* disclosing the source code of your own applications.
* 
* Contact: syblackwell@anywhichway.com
*/
var _createClass=function(){function b(b,h){for(var d=0;d<h.length;d++){var c=h[d];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(b,c.key,c)}}return function(c,h,d){h&&b(c.prototype,h);d&&b(c,d);return c}}(),_slicedToArray=function(){return function(b,c){if(Array.isArray(b))return b;if(Symbol.iterator in Object(b)){var h=[],d=!0,k=!1,g=void 0;try{for(var e=b[Symbol.iterator](),m;!(d=(m=e.next()).done)&&(h.push(m.value),!c||h.length!==c);d=!0);}catch(p){k=
!0,g=p}finally{try{if(!d&&e["return"])e["return"]()}finally{if(k)throw g;}}return h}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}(),_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b};
function _possibleConstructorReturn(b,c){if(!b)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!c||"object"!==typeof c&&"function"!==typeof c?b:c}
function _inherits(b,c){if("function"!==typeof c&&null!==c)throw new TypeError("Super expression must either be null or a function, not "+typeof c);b.prototype=Object.create(c&&c.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});c&&(Object.setPrototypeOf?Object.setPrototypeOf(b,c):b.__proto__=c)}function _classCallCheck(b,c){if(!(b instanceof c))throw new TypeError("Cannot call a class as a function");}
function _toConsumableArray(b){if(Array.isArray(b)){for(var c=0,h=Array(b.length);c<b.length;c++)h[c]=b[c];return h}return Array.from(b)}
(function e$jscomp$0(c,h,d){function k(e,p){if(!h[e]){if(!c[e]){var m="function"==typeof require&&require;if(!p&&m)return m(e,!0);if(g)return g(e,!0);m=Error("Cannot find module '"+e+"'");throw m.code="MODULE_NOT_FOUND",m;}m=h[e]={exports:{}};c[e][0].call(m.exports,function(n){var f=c[e][1][n];return k(f?f:n)},m,m.exports,e$jscomp$0,c,h,d)}return h[e].exports}for(var g="function"==typeof require&&require,e=0;e<d.length;e++)k(d[e]);return k})({1:[function(b,c,h){(function(){var b=arguments;c.exports=
function(c,d,e){if(d){var g="undefined"===typeof c?"undefined":_typeof(c);d.replace?d.replace[g]&&"object"===_typeof(d.replace[g])&&"undefined"!==typeof d.replace[g][c]?c=d.replace[g][c]:"undefined"!==typeof d.replace[g]&&(c=d.replace[g]):"undefined"!==typeof d.NA&&"undefined"===g?c=d.NA:"undefined"===typeof d.NaN||"number"===g&&!isNaN(c)||(c=d.NaN);3===b.length&&d["if"]&&!d["if"](c)&&(c=e)}return c}}).call(this)},{}],2:[function(b,c,h){(function(){c.exports=function(b,c){return function(d){return c?
d.map(b).reduce(function(b,c){return b.concat(c)},[]).reduce(function(b,d){return c(b,d)}):d.map(b).reduce(function(b,c){return b.concat(c)},[])}}}).call(this)},{}],3:[function(b,c,h){(function(){var b=function(){return new (Function.prototype.bind.apply(Date,[null].concat(Array.prototype.slice.call(arguments))))};b.now=Date.now;b.parse=Date.parse;b.UTC=Date.UTC;c.exports=new Proxy(b,{construct:function(b,c){return new (Function.prototype.bind.apply(Date,[null].concat(_toConsumableArray(c))))},get:function(b,
c){return["now","parse","UTC"].includes(c)?b[c]:new Proxy(function(){},{apply:function(b,d,g){var e;b=g[0];"string"===typeof b&&(b=new Date(b));"dayOfMonth"===c&&(c="Date");0!==c.indexOf("to")&&(c="get"+c[0].toUpperCase()+c.substring(1));return(e=b)[c].apply(e,_toConsumableArray(g.slice(1)))}})}})}).call(this)},{}],4:[function(b,c,h){(function(){c.exports=function(b,c){return Math.sqrt(b.reduce(function(d,e,m){return d+Math.pow(c[m]-b[m],2)},0))}}).call(this)},{}],5:[function(b,c,h){c.exports={};
c.exports.distance=b("./distance.js")},{"./distance.js":4}],6:[function(b,c,h){(function(){var d=b("../Unit/index.js");c.exports=function(b){return d.pow(b,1/3)}}).call(this)},{"../Unit/index.js":28}],7:[function(b,c,h){(function(){var d=b("../Unit/index.js");c.exports=function(b){return d.pow(b,3)}}).call(this)},{"../Unit/index.js":28}],8:[function(b,c,h){(function(){c.exports=function(b){var c=1;for(b=Math.round(b);b;)c*=b--;return c}}).call(this)},{}],9:[function(b,c,h){(function(){c.exports={};
c.exports.cbrt=b("./cbrt.js");c.exports.cube=b("./cube.js");c.exports.factorial=b("./factorial.js");c.exports.nthRoot=b("./nthRoot.js");c.exports.phi=b("./phi.js");c.exports.sign=b("./sign.js");c.exports.tau=b("./tau.js");c.exports.random=b("./random.js");c.exports.square=b("./square.js");c.exports.min=b("../min.js");c.exports.max=b("../max.js");var d=!0,k=!1,g=void 0;try{for(var e=function(){var b=p.value,e=b.toLowerCase();c.exports[e]||(c.exports[e]="function"===typeof Math[b]?Math[b]:function(){return Math[b]})},
m=Object.getOwnPropertyNames(Math)[Symbol.iterator](),p;!(d=(p=m.next()).done);d=!0)e()}catch(q){k=!0,g=q}finally{try{!d&&m["return"]&&m["return"]()}finally{if(k)throw g;}}}).call(this)},{"../max.js":49,"../min.js":50,"./cbrt.js":6,"./cube.js":7,"./factorial.js":8,"./nthRoot.js":10,"./phi.js":11,"./random.js":12,"./sign.js":13,"./square.js":14,"./tau.js":15}],10:[function(b,c,h){(function(){var d=b("../Unit/index.js");c.exports=function(b){return d.pow(b,1/(1<arguments.length&&void 0!==arguments[1]?
arguments[1]:2))}}).call(this)},{"../Unit/index.js":28}],11:[function(b,c,h){(function(){c.exports=function(){return(1+Math.sqrt(5))/2}}).call(this)},{}],12:[function(b,c,h){(function(){c.exports=function(b,c){return 2<=arguments.length?Math.floor(Math.random()*(c-b+1))+b:Math.random()}}).call(this)},{}],13:[function(b,c,h){(function(){var d=b("../isNumber.js");c.exports=function(b){return d(b)?0<b?1:0===b?0:-1:void 0}}).call(this)},{"../isNumber.js":44}],14:[function(b,c,h){(function(){var d=b("../Unit/index.js");
c.exports=function(b){return d.pow(b,2)}}).call(this)},{"../Unit/index.js":28}],15:[function(b,c,h){(function(){c.exports=function(){return 2*Math.PI}}).call(this)},{}],16:[function(b,c,h){(function(){function d(b,c){return b.length===c.length&&b.every(function(b,e){return b===c[e]})}function k(b){if(!Array.isArray(b))return[];var c=b.reduce(function(b,c){return d(b,k(c))?b:!1},k(b[0]));return c&&[b.length].concat(c)}function g(){}var e=b("../Vector/index.js");g.sum=function(){return[].slice.call(arguments).reduce(function(b,
c){for(var d=0;d<b.length;d++)b[d]=e.sum(b[d],Array.isArray(c)?c[d]:c);return b})};g.dimensions=k;g.invert=function(b){b=a;for(var c,e=b.length,d=[],f=0;f<e;f++)d[f]=[];for(f=0;f<e;f++)for(var l=0;l<e;l++)d[f][l]=0,f==l&&(d[f][l]=1);for(var g=0;g<e;g++){c=b[g][g];for(l=0;l<e;l++)b[g][l]/=c,d[g][l]/=c;for(f=g+1;f<e;f++)for(c=b[f][g],l=0;l<e;l++)b[f][l]-=b[g][l]*c,d[f][l]-=d[g][l]*c}for(g=e-1;0<g;g--)for(f=g-1;0<=f;f--)for(c=b[f][g],l=0;l<e;l++)b[f][l]-=b[g][l]*c,d[f][l]-=d[g][l]*c;for(f=0;f<e;f++)for(l=
0;l<e;l++)b[f][l]=d[f][l];return b};g.power=g.pow=function(b,c){for(;1<c--;)b=g.product(b,b.slice(0));return b};g.product=function(b,c){return b.map(function(b,d){return g.transpose(c.slice(0)).map(function(c){return e.dotProduct(b.slice(0),c.slice(0))})})};g.difference=function(){return[].slice.call(arguments).reduce(function(b,c){for(var d=0;d<b.length;d++)b[d]=e.difference(b[d],Array.isArray(c)?c[d]:c);return b})};g.transpose=function(b){return b[0].map(function(c,e){return b.map(function(b,c){return b[e]})})};
c.exports=g}).call(this)},{"../Vector/index.js":29}],17:[function(b,c,h){(function(){var d=b("../Unit/index.js");c.exports=function(){return d.parse(1.6021766208*Math.pow(10,-91)+" coulombs")}}).call(this)},{"../Unit/index.js":28}],18:[function(b,c,h){c.exports={};c.exports.c=b("./speedOfLight.js");c.exports.e=b("./elementaryCharge.js");c.exports.planks=c.exports.h=b("./planks.js")},{"./elementaryCharge.js":17,"./planks.js":19,"./speedOfLight.js":20}],19:[function(b,c,h){(function(){var d=b("../Unit/index.js");
c.exports=function(){return d.parse(6.62607004*Math.pow(10,34)+" m^2 kg / s")}}).call(this)},{"../Unit/index.js":28}],20:[function(b,c,h){(function(){var d=b("../Unit/index.js");c.exports=function(){return d.parse("299792458 m / s")}}).call(this)},{"../Unit/index.js":28}],21:[function(b,c,h){c.exports={};c.exports.average=b("../average.js");c.exports.count=b("../count.js");c.exports.madev=b("./madev.js");c.exports.max=b("../max.js");c.exports.median=b("./median.js");c.exports.min=b("../min.js");c.exports.mode=
b("./mode.js");c.exports.product=b("../product.js");c.exports.stdev=b("./stdev.js");c.exports.sum=b("../sum.js");c.exports.variance=b("./variance.js")},{"../average.js":32,"../count.js":34,"../max.js":49,"../min.js":50,"../product.js":54,"../sum.js":59,"./madev.js":22,"./median.js":23,"./mode.js":24,"./stdev.js":25,"./variance.js":26}],22:[function(b,c,h){(function(){var d=b("../average"),k=b("../flatten.js");b("../sum.js");c.exports=function(){var b=k([].slice.call(arguments),!0),c=d(b);return d(b.map(function(b){return Math.abs(b-
c)}))}}).call(this)},{"../average":32,"../flatten.js":39,"../sum.js":59}],23:[function(b,c,h){(function(){function d(b){if(!b.length)return 0;b=b.sort(function(b,c){return b-c});var c=Math.floor(b.length/2);return 0===b.length%2?(b[c]+b[c-1])/2:b[c]}var k=b("../../getArgs.js");c.exports=function(){var b=k([].slice.call(arguments,0));var c=_slicedToArray(b,2);b=c[0];c=c[1];1===b.length&&Array.isArray(b[0])&&(b=b[0]);c&&c["if"]&&(b=b.filter(c["if"]));return d(b)}}).call(this)},{"../../getArgs.js":63}],
24:[function(b,c,h){(function(){var d=b("../../getArgs.js");c.exports=function(){var b=d([].slice.call(arguments,0));var c=_slicedToArray(b,2);b=c[0];c=c[1];1===b.length&&Array.isArray(b[0])&&(b=b[0]);c&&c["if"]&&(b=b.filter(c["if"]));if(b.length){c={};var e=[],m=0,h=!0,q=!1,n=void 0;try{var f=b[Symbol.iterator]();for(var l;!(h=(l=f.next()).done);h=!0){var A=l.value,r=A.valueOf();c[r]?c[r]++:c[r]=1;c[r]>m?(e=[A],m=c[r]):c[r]===m&&(e.push(A),m=c[r])}}catch(K){q=!0,n=K}finally{try{!h&&f["return"]&&
f["return"]()}finally{if(q)throw n;}}f=e}else f=[];return f}}).call(this)},{"../../getArgs.js":63}],25:[function(b,c,h){(function(){var d=b("../average"),k=b("../flatten.js"),g=b("./variance.js");c.exports=function(){var b=k([].slice.call(arguments),!0);d(b);return b.length?Math.sqrt(g(b)):0}}).call(this)},{"../average":32,"../flatten.js":39,"./variance.js":26}],26:[function(b,c,h){(function(){var d=b("../average"),k=b("../flatten.js");b("../sum.js");c.exports=function(){var b=k([].slice.call(arguments),
!0),c=d(b);return b.reduce(function(b,d){return b+Math.pow(d-c,2)},0)/b.length}}).call(this)},{"../average":32,"../flatten.js":39,"../sum.js":59}],27:[function(b,c,h){(function(){c.exports=function(){return this?new (Function.prototype.bind.apply(String,[null].concat(Array.prototype.slice.call(arguments)))):String.apply(void 0,arguments)};var b=Object.getOwnPropertyDescriptors(String.prototype),k=function(b){"function"===typeof String.prototype[b]&&(c.exports[b]=function(){var c;return(c=String.prototype[b]).call.apply(c,
arguments)})},g;for(g in b)k(g);c.exports.reverse=function(b){return b.split("").reverse().join("")}}).call(this)},{}],28:[function(b,c,h){(function(){function d(){return{"boolean":{"true":1,"false":0},string:0,undefined:0,"null":0,Array:0}}function k(b,c,d){var f=b.baseUnits.split("/"),e=f[0].split(" ").filter(function(b){return"1"!=b&&""!==b}),f=f[1]?f[1].split(" ").filter(function(b){return"1"!=b&&""!==b}):[],l=c.split("/");c=(l[d?1:0]||"").split(" ").filter(function(b){return"1"!=b&&""!==b}).reduce(function(b,
c){var f=c.split("^"),d=f[0],f=f[1]?parseFloat(f[1]):1;b[d]=f;return b},{});l=(l[d?0:1]||"").split(" ").filter(function(b){return"1"!=b&&""!=b}).reduce(function(b,c){var f=c.split("^"),d=f[0],f=f[1]?parseFloat(f[1]):1;b[d]=f;return b},{});d={};for(var n=0;n<e.length;n++){var g=e[n].split("^");d[g[0]]=!0;g[1]=(g[1]?parseFloat(g[1]):1)+(c[g[0]]||0)-(l[g[0]]||0);0===g[1]?e.splice(n,1):e[n]=1===g[1]?g[0]:g.join("^")}for(n=0;n<f.length;n++)g=f[n].split("^"),d[g[0]]=!0,g[1]=(g[1]?parseFloat(g[1]):1)+(l[g[0]]||
0)-(c[g[0]]||0),0===g[1]?f.splice(n,1):f[n]=1===g[1]?g[0]:g.join("^");for(var k in l)n=l[k],d[k]||f.push(1<n?k+"^"+n:k);f.sort();for(var m in c)k=c[m],d[m]||e.push(1<k?m+"^"+k:m);e.sort();b.baseUnits=(0<e.length?e.join(" "):0<f.length?1:"")+(0<f.length?" / "+f.join(" "):"")}function g(b){var c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:Object.create(e.prototype);if(b&&"object"===("undefined"===typeof b?"undefined":_typeof(b))&&b instanceof e){for(var d=["value","units","baseUnits"],n=
0;n<d.length;n++){var g=d[n];c[g]=b[g]}Object.defineProperty(c,"constructor",{enumerable:!1,configurable:!0,writable:!0,value:e});return c}c.value=b;c.units={};c.baseUnits="";Object.defineProperty(c,"constructor",{enumerable:!1,configurable:!0,writable:!0,value:e});return c}function e(b,c,d){var f="undefined"===typeof b?"undefined":_typeof(b);if(!(this&&this instanceof e)&&b&&"object"===f&&b instanceof e)return b;if("string"===f){if(!(this&&this instanceof e))return new e(b,c,d);b=e.parse(b,d);for(var l in b)this[l]=
b[l]}else{if(!(this&&this instanceof e))return new e(b,c,d);b=m(b,d);if("number"===typeof b)g(b,this);else throw new TypeError("Can't create Unit from "+JSON.stringify(b));}c&&(l=e.getBase(c),l!==c&&(this.value*=e.getConversion(l,c)),this.baseUnits=l,c===this.baseUnits||(this.units[c]=this.baseUnits));Object.freeze(this)}var m=b("../../coerce.js");e.conversions={cm:{"in":2.54,m:100},ms:{s:1E3},g:{kg:1E3}};e.add=function(b,c,d){if("number"===typeof b&&"number"===typeof c)return b+m(c,d,0);b=g(e(b));
c=e(c,null,d);if(b.baseUnits===c.baseUnits||""===c.baseUnits)b.value+=m(c.value,d,0);else throw new TypeError("Incompatible "+b+" + "+c);return Object.freeze(b)};e.adda=function(b,c,l){l=Object.assign({replace:d()},l||{});return e.add(b,c,l)};e.as=function(b,c){"string"===typeof b&&(b=e.parse(b));var d=e.getConversion(b.baseUnits,c);if("number"===typeof d)return b.value*d};e.divide=function(b,c,d){if("number"===typeof b&&"number"===typeof c)return b/m(c,d,1);b=g(e(b));c=e(c,null,d);if(b.baseUnits===
c.baseUnits||e.isSimple(c))b.value/=m(c.value,d,1),c.baseUnits&&0<c.baseUnits.length&&k(b,c.baseUnits,!0);else throw new TypeError("Incompatible "+b+" / "+c);return Object.freeze(b)};e.dividea=function(b,c,l){l=Object.assign({replace:d()},l||{});return e.divide(b,c,l)};e.equal=function(b,c){if("number"===typeof b&&"number"===typeof c)return b===c;b=e(b);c=e(c);if(b.baseUnits===c.baseUnits||""===c.baseUnits)return b.value===c.value;throw new TypeError("Incompatible "+b+" + "+c);};e.isSimple=function(b){return b instanceof
e&&-1===b.baseUnits.indexOf(" ")};e.multiply=function(b,c,d){if("number"===typeof b&&"number"===typeof c)return b*m(c,d,1);b=g(e(b));c=e(c,null,d);if(b.baseUnits===c.baseUnits||e.isSimple(c))b.value*=m(c.value,d,1),c.baseUnits&&0<c.baseUnits.length&&k(b,c.baseUnits);else throw new TypeError("Incompatible "+b+" * "+c);return Object.freeze(b)};e.multiplya=function(b,c,l){l=Object.assign({replace:d()},l||{});return e.multiply(b,c,l)};e.pow=function(b,c){if("number"===typeof b)return Math.pow(b,c);b=
g(e(b));b.value=Math.pow(b.value,c);k(b,b.baseUnits);return Object.freeze(b)};e.subtract=function(b,c,d){if("number"===typeof b&&"number"===typeof c)return b-m(c,d,0);b=g(e(b));c=e(c,null,d);b.constructor=e;if(b.baseUnits===c.baseUnits||""===c.baseUnits)b.value-=m(c.value,d,0);else throw new TypeError("Incompatible "+b+" - "+c);return Object.freeze(b)};e.subtracta=function(b,c,l){l=Object.assign({replace:d()},l||{});return e.subtract(b,c,l)};e.to=function(b,c){var d=c.split(" ");b=g(e(b));var f=!0,
k=!1,m=void 0;try{for(var n=d[Symbol.iterator](),h;!(f=(h=n.next()).done);f=!0){var p=h.value;if("/"!==p){var q=e.getBase(p),v;for(v in b.units)v!==p&&b.units[v]===q&&(delete b.units[v],p!==q&&(b.units[p]=q))}}}catch(w){k=!0,m=w}finally{try{!f&&n["return"]&&n["return"]()}finally{if(k)throw m;}}return Object.freeze(b)};e.toJSON=function(b){return b.valueOf()};e.valueOf=function(b){var c=b.baseUnits,d=b.value,g=c.split(" "),k;for(k in b.units){var m=b.units[k];if(0<=c.indexOf(m)){var h=!0,n=!1,p=void 0;
try{for(var q=g[Symbol.iterator](),v;!(h=(v=q.next()).done);h=!0){var w=v.value;if("/"!==w){var y=1;if(0===w.indexOf(m)){var B=w.split("^");B[0]===m&&B[1]&&(y=parseFloat(B[1]))}d/=Math.pow(e.getConversion(m,k),y);c=c.replace(new RegExp(" "+m+"(\\^?-?\\d*\\.?\\d?)* ","g")," "+k+"$1 ").replace(new RegExp("^"+m+"(\\^?-?\\d*\\.?\\d?\\s)"),k+"$1").replace(new RegExp(m+"(\\^?-?\\d*\\.?\\d?$)"),k+"$1");break}}}catch(C){n=!0,p=C}finally{try{!h&&q["return"]&&q["return"]()}finally{if(n)throw p;}}}}return d+
" "+c};var h=function(b){"function"===typeof e[b]&&(e.prototype[b]=function(){return e[b].apply(e,[this].concat(Array.prototype.slice.call(arguments)))})},q;for(q in e)h(q);e.getBase=function(b){for(var c in e.conversions)if(c===b||"number"===typeof e.conversions[c][b])return c};e.getConversion=function(b,c){if(b===c)return 1;var d=e.getBase(b);if(d&&e.conversions[d][c])return e.conversions[d][c];if((d=e.getBase(c))&&e.conversions[d][b])return 1/e.conversions[d][b]};e.max=function(b,c){if("number"===
typeof b&&"number"===typeof c)return Math.max(b,c);b=g(e(b));c=e(c);return b.value>c.value?b:c};e.min=function(b,c){if("number"===typeof b&&"number"===typeof c)return Math.min(b,c);b=g(e(b));c=e(c);return b.value<c.value?b:c};e.parse=function(b,c){var d=g(),f=b.trim().split(" "),k=parseFloat(f[0]);d.value=m(k,c);for(var k=!1,h=1;h<f.length;h++){var n=f[h];if("/"===n)k=!0,d.baseUnits+=" /";else{var p=n.split("^"),q=e.getBase(p[0]),x=p[1]?parseFloat(p[1]):1;n!==q&&(d.units[p[0]]=q,n=Math.pow(e.conversions[q][p[0]],
x),d.value=k?d.value/n:d.value*n);d.baseUnits+=(0<d.baseUnits.length?" ":"")+q+(0!==x&&1!==x?"^"+x:"")}}return Object.freeze(d)};c.exports=e}).call(this)},{"../../coerce.js":1}],29:[function(b,c,h){(function(){function d(){var b=new Proxy(new (Function.prototype.bind.apply(Array,[null].concat(Array.prototype.slice.call(arguments)))),{get:function(b,c){var e=Object.getOwnPropertyDescriptor(b,c);return e?e.value:(e=Object.getOwnPropertyDescriptor(d.prototype,c))?e.value:b[c]},set:function(b,c,d){if("number"!==
typeof arg)error("set: Vectors can only contain numbers!");else return b[c]=d,!0},deleteProperty:function(b,c){Object.defineProperty(b,c,{value:void 0});return!0}});[].forEach(function(c){return delete b[c]});return b}var k=b("../add.js"),g=b("../divide.js"),e=b("../multiply.js"),m=b("../pow.js"),h=b("../subtract.js"),q=b("../Unit/index.js");d.prototype=[];["push","unshift","splice"].forEach(function(b){d.prototype[b]=function(){var c;if([].slice.call(arguments).some(function(b){return Array.isArray(b)}))error(b+
": Vectors can only have one dimension!");else return(c=[].push).call.apply(c,[this].concat(Array.prototype.slice.call(arguments)))}});d.prototype.concat=function(){var b;if([].slice.call(arguments).some(function(b){return Array.isArray(b)&&b.some(function(b){return Array.isArray(b)})}))error("concat: Vectors can only have one dimension!");else return(b=[].concat).call.apply(b,[this].concat(Array.prototype.slice.call(arguments)))};d.reduce=function(b,c){return b.reduce(function(b,d){for(var e=0;e<
b.length;e++)b[e]=c(b[e],Array.isArray(d)?d[e]:d);return b})};d.map=function(b,c){return b.map(c)};d.sum=function(){return d.reduce([].slice.call(arguments),k)};d.average=function(){var b=[].slice.call(arguments);return d.reduce(b,k).map(function(c){return q.divide(c,b.length)})};d.product=d.crossProduct=function(b,c){return 2===b.length?b[0]*c[1]-b[1]*c[0]:[b[1]*c[2]-b[2]*c[1],b[2]*c[0]-b[0]*c[2],b[0]*c[1]-b[1]*c[0]]};d.scalarQuotient=function(){return d.reduce([].slice.call(arguments),g)};d.dotProduct=
function(){return d.reduce([].slice.call(arguments),e).reduce(k)};d.scalarProduct=function(){return d.reduce([].slice.call(arguments),e)};d.pow=function(){return d.reduce([].slice.call(arguments),m)};d.difference=function(){return d.reduce([].slice.call(arguments),h)};var n=function(b){"function"===typeof d[b]&&(d.prototype[b]=function(){return d[b].apply(d,[this].concat(Array.prototype.slice.call(arguments)))})},f;for(f in d)n(f);c.exports=d}).call(this)},{"../Unit/index.js":28,"../add.js":30,"../divide.js":36,
"../multiply.js":51,"../pow.js":53,"../subtract.js":57}],30:[function(b,c,h){(function(){var d=b("./Unit/index.js");c.exports=function(b,c,e){return d.add(b,c,e)}}).call(this)},{"./Unit/index.js":28}],31:[function(b,c,h){(function(){var d=b("./Unit/index.js");c.exports=function(b,c,e){return d.adda(b,c,e)}}).call(this)},{"./Unit/index.js":28}],32:[function(b,c,h){(function(){var d=b("./add.js"),k=b("./isNumber.js"),g=b("./flattenReduce.js"),e=b("./divide.js");c.exports=function(){var b=1;return 0===
arguments.length?NaN:e(g([].slice.call(arguments),function(c,e,g){return k(e)?(b++,d(c,e,g)):c},!0),b)}}).call(this)},{"./add.js":30,"./divide.js":36,"./flattenReduce.js":40,"./isNumber.js":44}],33:[function(b,c,h){(function(){var d=b("./adda.js"),k=b("./flattenReduce.js"),g=b("./divide.js");c.exports=function(){var b=1;return 0===arguments.length?NaN:g(k([].slice.call(arguments),function(c,e,g){b++;return d(c,e,g)},!0),b)}}).call(this)},{"./adda.js":31,"./divide.js":36,"./flattenReduce.js":40}],
34:[function(b,c,h){(function(){var d=b("./flattenReduce.js");c.exports=function(){var b=1;if(0===arguments.length)return 0;d([].slice.call(arguments),function(c,d){b++},!0);return b}}).call(this)},{"./flattenReduce.js":40}],35:[function(b,c,h){(function(){function b(b,c){return b.length===c.length&&b.every(function(b,d){return b===c[d]})}function k(c){if(!Array.isArray(c))return[];var d=c.reduce(function(c,d){return b(c,k(d))?c:!1},k(c[0]));return d&&[c.length].concat(d)}c.exports=k}).call(this)},
{}],36:[function(b,c,h){(function(){var d=b("./Unit/index.js");c.exports=function(b,c,e){return d.divide(b,c,e)}}).call(this)},{"./Unit/index.js":28}],37:[function(b,c,h){(function(){var d=b("./Unit/index.js");c.exports=function(b,c,e){return d.dividea(b,c,e)}}).call(this)},{"./Unit/index.js":28}],38:[function(b,c,h){(function(){var d=b("./Unit/index.js"),k=function(b,c){return b.length===c.length&&b.every(function(b,d){return g(b,c[d])})},g=function(b,c){return b===c||(Array.isArray(b)?Array.isArray(c)&&
k(b,c):d.equal(b,c))};c.exports=g}).call(this)},{"./Unit/index.js":28}],39:[function(b,c,h){(function(){var d=b("../concatMapReduce.js"),k=d(function(b){return b}),g=d(function(b){return Array.isArray(b)?g(b):b});c.exports=function(b,c){return(c?g:k)(b)}}).call(this)},{"../concatMapReduce.js":2}],40:[function(b,c,h){(function(){var d=b("../concatMapReduce.js"),k=function(b,c){return d(id,c)(b)},g=function m(b,c){return d(function(b){return Array.isArray(b)?m(b):b},c)(b)};c.exports=function(b,c,d){return(d?
g:k)(b,c)}}).call(this)},{"../concatMapReduce.js":2}],41:[function(b,c,h){(function(){c.exports=function(b){return"function"===typeof b}}).call(this)},{}],42:[function(b,c,h){(function(){c.exports=function(b){return Array.isArray(b)&&Array.isArray(b[0])&&Array.isArray(b[b.length-1])}}).call(this)},{}],43:[function(b,c,h){(function(){c.exports=function(b){return 0>b}}).call(this)},{}],44:[function(b,c,h){(function(){c.exports=function(b){return"number"===typeof b}}).call(this)},{}],45:[function(b,
c,h){(function(){c.exports=function(b){return 0<b}}).call(this)},{}],46:[function(b,c,h){(function(){c.exports=function(b){for(var c=2,d=Math.sqrt(b);c<=d;c++)if(0===b%c)return!1;return 1!==b}}).call(this)},{}],47:[function(b,c,h){(function(){c.exports=function(b){return Array.isArray(b)&&!Array.isArray(b[0])&&!Array.isArray(b[b.length-1])}}).call(this)},{}],48:[function(b,c,h){(function(){var d=b("../getArgs.js"),k=b("../traverse.js");c.exports=function e(){var b=d([].slice.call(arguments,0)),b=
_slicedToArray(b,2),c=b[0],h=b[1],n=c[c.length-1],f="";k(c.slice(0,c.length-1),function(b){return f+=Array.isArray(b)?e.apply(void 0,_toConsumableArray(b).concat([n,h])):(0<f.length?n:"")+b});return f}}).call(this)},{"../getArgs.js":63,"../traverse.js":65}],49:[function(b,c,h){(function(){var d=b("../getArgs.js"),k=b("./add.js"),g=b("./flattenReduce.js"),e=b("./Unit/index.js");c.exports=function(){var b=d([].slice.call(arguments,0)),b=_slicedToArray(b,2),c=b[0],h=b[1];return 0===c.length?-Infinity:
k(g([].slice.call(c),function(b,c){return e.max(b,c,h)},!0),0)}}).call(this)},{"../getArgs.js":63,"./Unit/index.js":28,"./add.js":30,"./flattenReduce.js":40}],50:[function(b,c,h){(function(){var d=b("../getArgs.js"),k=b("./add.js"),g=b("./flattenReduce.js"),e=b("./Unit/index.js");c.exports=function(){var b=d([].slice.call(arguments,0)),b=_slicedToArray(b,2),c=b[0],h=b[1];return 0===c.length?Infinity:k(g([].slice.call(c),function(b,c){return e.min(b,c,h)},!0),0)}}).call(this)},{"../getArgs.js":63,
"./Unit/index.js":28,"./add.js":30,"./flattenReduce.js":40}],51:[function(b,c,h){(function(){var d=b("./Unit/index.js");c.exports=function(b,c){return d.multiply(b,c)}}).call(this)},{"./Unit/index.js":28}],52:[function(b,c,h){(function(){var d=b("./Unit/index.js");c.exports=function(b,c,e){return d.multiplya(b,c,e)}}).call(this)},{"./Unit/index.js":28}],53:[function(b,c,h){(function(){var d=b("./Unit/index.js");c.exports=function(b,c){return d.pow(b,c)}}).call(this)},{"./Unit/index.js":28}],54:[function(b,
c,h){(function(){var d=b("../getArgs.js"),k=b("./add.js"),g=b("./flattenReduce.js"),e=b("./multiply.js");c.exports=function(){var b=d([].slice.call(arguments,0)),b=_slicedToArray(b,2),c=b[1];return k(g([].slice.call(b[0]),function(b,d){return e(b,d,c)},!0),0)}}).call(this)},{"../getArgs.js":63,"./add.js":30,"./flattenReduce.js":40,"./multiply.js":51}],55:[function(b,c,h){(function(){var d=b("../getArgs.js"),k=b("./add.js"),g=b("./flattenReduce.js"),e=b("./multiplya.js");c.exports=function(){var b=
d([].slice.call(arguments,0)),b=_slicedToArray(b,2),c=b[1];return k(g([].slice.call(b[0]),function(b,d){return e(b,d,c)},!0),0)}}).call(this)},{"../getArgs.js":63,"./add.js":30,"./flattenReduce.js":40,"./multiplya.js":52}],56:[function(b,c,h){(function(){var d=b("./add.js"),k=b("./divide.js"),g=b("./flattenReduce.js");c.exports=function(){return d(g([].slice.call(arguments),k,!0),0)}}).call(this)},{"./add.js":30,"./divide.js":36,"./flattenReduce.js":40}],57:[function(b,c,h){(function(){var d=b("./Unit/index.js");
c.exports=function(b,c,e){return d.subtract(b,c,e)}}).call(this)},{"./Unit/index.js":28}],58:[function(b,c,h){(function(){var d=b("./Unit/index.js");c.exports=function(b,c,e){return d.subtracta(b,c,e)}}).call(this)},{"./Unit/index.js":28}],59:[function(b,c,h){(function(){var d=b("../getArgs.js"),k=b("./add.js"),g=b("./flattenReduce.js");c.exports=function(){var b=d([].slice.call(arguments,0)),b=_slicedToArray(b,2),c=b[1];return k(g([].slice.call(b[0]),function(b,d){return k(b,d,c)},!0),0)}}).call(this)},
{"../getArgs.js":63,"./add.js":30,"./flattenReduce.js":40}],60:[function(b,c,h){(function(){var d=b("../getArgs.js"),k=b("./add.js"),g=b("./adda.js"),e=b("./flattenReduce.js");c.exports=function(){var b=d([].slice.call(arguments,0)),b=_slicedToArray(b,2),c=b[1];return k(e([].slice.call(b[0]),function(b,d){return g(b,d,c)},!0),0)}}).call(this)},{"../getArgs.js":63,"./add.js":30,"./adda.js":31,"./flattenReduce.js":40}],61:[function(b,c,h){(function(){c.exports=function(b){var c=1<arguments.length&&
void 0!==arguments[1]?arguments[1]:{};return(new Function("value","return `"+(c.template?c.template:"${value}")+"`"))(b)}}).call(this)},{}],62:[function(b,c,h){(function(){c.exports=function(b){var c="undefined"===typeof b?"undefined":_typeof(b);return null===b||void 0===b?"undefined":Array.isArray(b)?"Array":"object"===c?b.constructor.name:c}}).call(this)},{}],63:[function(b,c,h){(function(){function b(c){b.VARGS=[];var d=c[c.length-1],d=d&&"object"===("undefined"===typeof d?"undefined":_typeof(d))&&
!Array.isArray(d)?d:null;!d||(c=c.slice(0,c.length-1));for(var e=[],h=0;h<c.length;h++)if(c[h]===b.VARGS){var k=b.VARGS.shift();if(Array.isArray(k)){var q=!0,n=!1,f=void 0;try{for(var l=k[Symbol.iterator](),A;!(q=(A=l.next()).done);q=!0)e.push(A.value)}catch(r){n=!0,f=r}finally{try{!q&&l["return"]&&l["return"]()}finally{if(n)throw f;}}}else results.push(k)}else e.push(c[h]);return[e,d]}c.exports=b}).call(this)},{}],64:[function(b,c,h){(function(){function d(b){b=Array.isArray(b)?b.slice(0):[].slice.call(arguments,
0);var c=mean(b),d=stdev(b);return b.map(function(b){return(b-c)/d})}function h(){return{"boolean":{"true":1,"false":0},string:0,undefined:0,"null":0,Array:0}}function g(b,c){if(c){var d="undefined"===typeof b?"undefined":_typeof(b);if(c.replace){if(c.replace[d]&&"object"===_typeof(c.replace[d])&&"undefined"!==typeof c.replace[d][b])return c.replace[d][b];if("undefined"!==typeof c.replace[d])return c.replace[d]}if("undefined"!==typeof c.NA&&"undefined"===d)return c.NA;if("undefined"!==typeof c.NaN&&
"number"!==d)return c.NaN}return b}function e(b){var c=b[b.length-1],c=c&&"object"===("undefined"===typeof c?"undefined":_typeof(c))&&!Array.isArray(c)?c:null;!c||(b=b.slice(0,b.length-1));for(var d=[],e=0;e<b.length;e++)if(b[e]===n){var f=n.shift();if(Array.isArray(f)){var g=!0,l=!1,h=void 0;try{for(var k=f[Symbol.iterator](),m;!(g=(m=k.next()).done);g=!0)d.push(m.value)}catch(y){l=!0,h=y}finally{try{!g&&k["return"]&&k["return"]()}finally{if(l)throw h;}}}else results.push(f)}else d.push(b[e]);n.splice(0,
n.length);return[d,c]}function m(b,c){var d=b.split("."),e=c.split(".");return d.length===e.length&&d.every(function(b,c){var d=b.split(":");return 1===d.length?"*"===d[0]||d[0]===e[c]:"*"===d[0]||e[c]>=d[0]?"*"===d[1]||e[c]<=d[1]:!1})}function p(){function c(b,d,e){var f=c.cells[b];if(!(this&&this instanceof c)){if(!f)return new c(b,d,e);if(1===arguments.length)return f;f.value=d;f.options||(f.options={});!e||Object.assign(f.options,e);return f}Object.defineProperty(this,"engine",{enumerable:!1,
configurable:!0,writable:!0,value:r});this.coordinates=b;this.options={};this.computed=null;Object.assign(this.options,e);Object.defineProperty(this,"references",{enumerable:!1,configurable:!0,writable:!0,value:{}});this.data=d;Object.defineProperty(this,"calculating",{writable:!0});Object.defineProperty(this,"value",{enumerable:!1,configurable:!0,get:function(){return this.valueOf()},set:function(b){"string"===typeof b&&b==parseFloat(b)&&(b=parseFloat(b));this.data=b;this.compile().calc();return!0}});
this.compile().calc();return this}var k=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{},r=this,p=void 0;r.options=Object.assign({},k);r.calculating=0;Object.defineProperty(r,"oncalculated",{enumerable:!1,configurable:!0,writable:!0,value:k.oncalculated});f.Date=b("./functions/Date/index.js");f.now=f.Date.now;f.UTC=f.Date.UTC;var k=!0,H=!1,I=void 0;try{for(var L=function(){var b=v.value;if(0===b.indexOf("get")||0===b.indexOf("to"))0===b.indexOf("get")&&(b=b.substring(3)),"Date"===b&&(b="dayOfMonth"),
"U"!==b[0]&&(b=b[0].toLowerCase()+b.substring(1)),f[b]=function(){var c;return(c=f.Date)[b].apply(c,arguments)}},x=Object.getOwnPropertyNames(Date.prototype)[Symbol.iterator](),v;!(k=(v=x.next()).done);k=!0)L()}catch(u){H=!0,I=u}finally{try{!k&&x["return"]&&x["return"]()}finally{if(H)throw I;}}f.Geometry=b("./functions/Geometry/index.js");f.Math=b("./functions/Math/index.js");for(var w in f.Math)f[w]=f.Math[w];f.Matrix=b("./functions/Matrix/index.js");f.Physics=b("./functions/Physics/index.js");f.Statistics=
b("./functions/Statistics/index.js");for(var y in f.Statistics)f[y]=f.Statistics[y];f.String=b("./functions/String/index.js");for(var B in f.String)f[B]=f.String[B];f.Unit=b("./functions/Unit/index.js");f.Vector=b("./functions/Vector/index.js");f.add=b("./functions/add.js");f.adda=b("./functions/adda.js");f.average=b("./functions/average.js");f.averagea=b("./functions/averagea.js");f.count=b("./functions/count.js");f.dimensions=b("./functions/dimensions.js");f.divide=b("./functions/divide.js");f.dividea=
b("./functions/dividea.js");f.equal=b("./functions/equal.js");f.flatten=b("./functions/flatten.js");f.isFunction=b("./functions/isFunction.js");f.isMatrix=b("./functions/isMatrix.js");f.isNegative=b("./functions/isNegative.js");f.isNumeric=f.isNumber=b("./functions/isNumber.js");f.isPositive=b("./functions/isPositive.js");f.isPrime=b("./functions/isPrime.js");f.isVector=b("./functions/isVector.js");f.join=b("./functions/join.js");f.multiply=b("./functions/multiply.js");f.multiplya=b("./functions/multiplya.js");
f.product=b("./functions/product.js");f.producta=b("./functions/producta.js");f.power=f.pow=b("./functions/pow.js");f.quotient=b("./functions/quotient.js");f.subtract=b("./functions/subtract.js");f.subtracta=b("./functions/subtracta.js");f.sum=b("./functions/sum.js");f.suma=b("./functions/suma.js");f.text=b("./functions/text.js");f.type=b("./functions/type.js");f.range=function(b,c){var d=[],e=f.cells(b),g=!0,h=!1,u=void 0;try{for(var k=e[Symbol.iterator](),t;!(g=(t=k.next()).done);g=!0){var l=t.value;
c&&c["if"]?!c["if"](l.value)||d.push(l.value):d.push(l.value)}}catch(E){h=!0,u=E}finally{try{!g&&k["return"]&&k["return"]()}finally{if(h)throw u;}}return d};f.summary=function(b){var c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{result:"array",values:["min","average","max"]},d="array"===c.result?[]:{},e=[],g=f.cells(b),h=!0,u=!1,k=void 0;try{for(var l=g[Symbol.iterator](),m;!(h=(m=l.next()).done);h=!0){var n=m.value;c&&c["if"]?!c["if"](n.value)||e.push(n.value):e.push(n.value)}}catch(F){u=
!0,k=F}finally{try{!h&&l["return"]&&l["return"]()}finally{if(u)throw k;}}g=!0;h=!1;u=void 0;try{for(var p=c.values[Symbol.iterator](),q;!(g=(q=p.next()).done);g=!0){var r=q.value,v=f.Statistics[r](e);"array"===c.result?d.push(v):d[r]=v}}catch(F){h=!0,u=F}finally{try{!g&&p["return"]&&p["return"]()}finally{if(h)throw u;}}return d};f.interval=function(b,c){var d=p;setInterval(function(){d.calc()},b);return"="+c};f.destructure=f.varg=function(b){n.push(b);return n};f.values=function(b,c){var d=[],e=f.cells(b);
c=Object.assign({replace:h()},c||{});var u=!0,k=!1,t=void 0;try{for(var l=e[Symbol.iterator](),m;!(u=(m=l.next()).done);u=!0){var n=m.value;c&&c["if"]?!c["if"](n.value)||d.push(g(n.value,c)):d.push(g(n.value,c))}}catch(E){k=!0,t=E}finally{try{!u&&l["return"]&&l["return"]()}finally{if(k)throw t;}}return d};f.cells=function(b){if(p){var d=c.observers[b];d||(d={},c.observers[b]=d);d[p.coordinates]=!0}return c.find(b,c.cellIndex)};f.counta=function(){var b=void 0,c=void 0,b=e([].slice.call(arguments,
0)),c=_slicedToArray(b,2),b=c[0];(c=c[1])&&c["if"]&&(b=b.filter(c["if"]));b=b.filter(function(b){return null!==b&&"undefined"!==typeof b});return b.length};f.extend=function(){var b=p.coordinates.split("."),d=p.engine.sheets[b[0]],f=parseInt(b[2]),g=p.data,h=parseInt(b[1]),k=h,l=f,m=void 0,b=e([].slice.call(arguments,0)),m=_slicedToArray(b,2)[0];p.compiled=function(){for(var b=0;b<m.length;b++)for(var e=0;e<m[b].length;e++,k++){var g=m[b][e];Array.isArray(g)&&(l=Math.max(l,f+(g.length-1)))}for(b=
f;b<=l;b++)d.createRow(b,Array(k-h));b=h;for(e=0;e<m.length;e++)for(var g=0,u=f;g<m[e].length;g++,b++){var z=m[e][g];if(Array.isArray(z))for(var t=0;t<z.length;t++)c(d.name+"."+b+"."+(u+t),z[t]);else c(d.name+"."+b+"."+u,z)}this.computed=Array.isArray(m[0][0])?m[0][0][0]:m[0][0]};p.data=g;p.compiled();return p.computed};f.maxa=function(){var b=void 0,c=void 0,b=e([].slice.call(arguments,0)),c=_slicedToArray(b,2),b=c[0],c=c[1];Array.isArray(b[0])&&(b=b[0]);c&&c["if"]&&(b=b.filter(c["if"]));if(0===
b.length)return-Infinity;c=Object.assign({replace:h()},c||{});q(b,function(b,c,d){return d[c]=g(b,{replace:h()})});return b.reduce(function(b,c){return Math.max(b,c)})};f.mina=function(){var b=void 0,c=void 0,b=e([].slice.call(arguments,0)),c=_slicedToArray(b,2),b=c[0],c=c[1];Array.isArray(b[0])&&(b=b[0]);c&&c["if"]&&(b=b.filter(c["if"]));if(0===b.length)return Infinity;c=Object.assign({replace:h()},c||{});q(b,function(b,c,d){return d[c]=g(b,{replace:h()})});return b.reduce(function(b,c){return Math.min(b,
c)})};f.quotienta=function(){var b=void 0,c=void 0,b=e([].slice.call(arguments,0)),d=_slicedToArray(b,2),b=d[0],c=d[1],c=Object.assign({replace:{"boolean":1,string:1,undefined:1}},c||{});c["if"]&&(b=b.filter(c["if"]));if(0===b.length)return Infinity;c=Object.assign({"boolean":{"true":1,"false":0},string:1,undefined:1,"null":1,Array:1},c||{});q(b,function(b,d,e){return e[d]=g(b,{replace:c})});return f.quotient.apply(f,_toConsumableArray(b))};f.remaindera=function(){var b=void 0,c=void 0,b=e([].slice.call(arguments,
0)),d=_slicedToArray(b,2),b=d[0],c=d[1];(c=Object.assign({replace:h()},c||{}))&&c["if"]&&(b=b.filter(c["if"]));return b.reduce(function(b,d){return b-g(d,c)},0)};f.zscores=function(){var b=void 0,c=void 0,b=e([].slice.call(arguments,0)),c=_slicedToArray(b,2),b=c[0],c=c[1];Array.isArray(b[0])&&(b=b[0]);b=b.filter(function(b){return"number"===typeof b});c&&c["if"]&&(b=b.filter(c["if"]));return 0===b.length?0:d(b)};r.functions=new Proxy(f,{set:function(b,c,d){if("function"!==typeof d)throw Error("Hypercalc custom function must be a function: ",
d);b[c]=d;return!0}});c.prototype.addReferences=function(){for(var b=0;b<arguments.length;b++)arguments[b]===this||(this.references[arguments[b].coordinates]=!0)};c.prototype.deleteReferences=function(){for(var b=0;b<arguments.length;b++)delete this.references[arguments[b].coordinates]};c.prototype.clearReferences=function(){this.references={}};c.prototype.compile=function(){delete this.compiled;this.index();if("string"===typeof this.data&&0===this.data.indexOf("=")){var b=this.data.substring(1),
b=b.replace(/\$\((.*?)\)/g,"range('$1')"),b=b.replace(/\$summary\((.*?)\)/g,"summary('$1')"),b=b.replace(/\$a\((.*?)\)/g,"values('$1')");Object.defineProperty(this,"compiled",{enumerable:!1,configurable:!0,writable:!0,value:(new Function("functions","return function() { with(functions) { return "+b+"; }}"))(f)})}for(var d in c.observers){var b=[],e;for(e in c.observers[d])b.push(c.cells[e]);m(d,this.coordinates)&&this.addReferences.apply(this,b)}return this};c.prototype.calc=function(){function b(){if(e.compiled){var b=
p;p=e;var c=e.compiled();"string"===typeof c&&0===c.indexOf("=")&&(c=(new Function("return "+c.substring(1)))()());e.computed=c;p=b}!e.options.oncalculated||e.options.oncalculated(e);e.engine.calculating--;e.calculating=null;if(!e.engine.calculating&&e.engine.oncalculated)e.engine.oncalculated(e.engine)}var d=0<arguments.length&&void 0!==arguments[0]?arguments[0]:!0,e=this;e.calculating||(e.calculating=setTimeout(b),e.engine.calculating++);if(d)for(var f in e.references)c.cells[f].calc()};c.prototype.index=
function(){var b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:c.cellIndex;b===c.cellIndex?c.cells[this.coordinates]=this:b===c.observerIndex&&(c.observers[this.data]=this);for(var d=this.coordinates.split("."),b=b.nodes,e=0;e<d.length;e++)b[d[e]]||(b[d[e]]={nodes:{}}),e===d.length-1?b[d[e]].coordinates=this.coordinates:b=b[d[e]].nodes};c.prototype.valueOf=function(){!p||this.addReferences(p);return this.compiled?this.computed:this.data};c.find=function(b){function d(b,e,f,g){if(e)if(f===
b.length){var h=c.cells[e.coordinates];!h||g.push(h)}else{e=e.nodes;var k=b[f],l=k.includes(":")?":":k.includes("|")?"|":null;if(l){var m=k.split(l),n=!1;if(":"===l)for(var p=0;p<m.length;p++)parseInt(m[p])==m[p]&&(m[p]=parseInt(m[p]),n=!0);var p=Object.keys(e),z=f+1,D=!0;f=!1;k=void 0;try{for(var q=function(){var c=J.value;":"===l?(c=n&&parseInt(c)==c?parseInt(c):c,("*"===m[0]||c>=m[0])&&c<=m[1]&&d(b,e[c],z,g)):m.some(function(b){return b==c})&&d(b,e[c],z,g)},h=p[Symbol.iterator](),J;!(D=(J=h.next()).done);D=
!0)q()}catch(G){f=!0,k=G}finally{try{!D&&h["return"]&&h["return"]()}finally{if(f)throw k;}}}else if("*"===k){h=Object.keys(e);f+=1;var k=!0,q=!1,r=void 0;try{for(p=h[Symbol.iterator]();!(k=(D=p.next()).done);k=!0)d(b,e[D.value],f,g)}catch(G){q=!0,r=G}finally{try{!k&&p["return"]&&p["return"]()}finally{if(q)throw r;}}}else e=e[k],d(b,e,++f,g)}}var e=1<arguments.length&&void 0!==arguments[1]?arguments[1]:c.cellIndex,f=[];d(b.split("."),e,0,f);return f};c.cells={};c.observers={};c.cellIndex={nodes:{}};
c.observerIndex={nodes:{}};r.Cell=c;var C=function t(b,d,e){_classCallCheck(this,t);Object.defineProperty(this,"engine",{enumerable:!1,configurable:!0,writable:!0,value:r});this.sheet=b.name;this.cells={};d||(d=b.rows.length+1);this.id=d;t.rows[d]=this;var f=0;if(b.options.columns)if(Array.isArray(e))for(var g=Object.keys(b.options.columns),h=0;h<e.length;h++){var k=g[h]||h,k=c(b.name+"."+k+"."+d,e[h],b.options.columns[k]);this.cells[k.coordinates]=!0}else for(g in b.options.columns)h=c(b.name+"."+
g+"."+d,e[g],b.options.columns[g]),this.cells[h.coordinates]=!0;else if(Array.isArray(e))for(g=0;g<e.length;g++,f++)h=c(b.name+"."+(g+1)+"."+d,e[g],{}),this.cells[h.coordinates]=!0;else for(g=Object.keys(e),h=0;h<e.length;h++,f++)k=c(b.name+"."+(h+1)+"."+d,e[g[h]],{}),this.cells[k.coordinates]=!0;if(b.options.columnCount&&f<b.options.columnCount)for(;f++<b.options.columnCount;)e=c(b.name+"."+f+"."+d,null,{}),this.cells[e.coordinates]=!0};C.rows={};r.Space=function(){function b(c){var d=1<arguments.length&&
void 0!==arguments[1]?arguments[1]:{sparse:r.options.sparse};_classCallCheck(this,b);Object.defineProperty(this,"engine",{enumerable:!1,configurable:!0,writable:!0,value:r});var e=r.spaces[c];if(e||!this)return e;this.name=c;this.options={};Object.assign(this.options,d);this.cells={};r.spaces[c]=this}_createClass(b,[{key:"createCell",value:function(b,d,e){b=this.name+"."+b;d=new c(b,d,e);this.cells[b]=!0;return d}},{key:"createVector",value:function(b,d){var e=this,f=this.name+".";Object.keys(this.options.dimensions).forEach(function(c,
d,g){if(!["number","boolean","string"].includes(_typeof(b[c])))throw Error("Incompatible vector "+e.name);f+=b[c]+(d<g.length-1?".":"")});c(f,d,this.options.contains,this)}},{key:"export",value:function(){var b={},d={};if((0<arguments.length&&void 0!==arguments[0]?arguments[0]:{cells:!0,sparse:!0}).cells){b.cells={};for(var e in this.cells)d[e]||(b.cells[e.split(".").slice(1).join(".")]=c.cells[e].value)}return b}}]);return b}();r.spaces={};r.Sheet=function(b){function d(b){var c=1<arguments.length&&
void 0!==arguments[1]?arguments[1]:{sparse:r.options.sparse};_classCallCheck(this,d);var c=_possibleConstructorReturn(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,b,c)),e=r.sheets[b];if(e||!c)return _possibleConstructorReturn(c,e);c.rows=[];return r.sheets[b]=c}_inherits(d,b);_createClass(d,[{key:"createRow",value:function(b,c){var d=new C(this,b,c);this.rows.push(d.id);return d}},{key:"import",value:function(b,c){for(var d=0;d<b.length;d++)this.createRow(d+1,b[d])}},{key:"export",value:function(){var b=
0<arguments.length&&void 0!==arguments[0]?arguments[0]:{rows:!0,cells:!1,sparse:!0},d={},e={};if(b.rows)if(0<this.rows.length){var f=["Row/Col"];d.rows=[f];var g=!0,h=!1,k=void 0;try{for(var l=this.rows[Symbol.iterator](),m;!(g=(m=l.next()).done);g=!0){var n=m.value,p=[];p.push(n);d.rows.push(p);for(var q in C.rows[n].cells){var r=q.split("."),v=_slicedToArray(r,2)[1];e[q]=!0;f.includes(v)||f.push(v);p.push(b.extended?c.cells[q]:c.cells[q].value)}}}catch(M){h=!0,k=M}finally{try{!g&&l["return"]&&l["return"]()}finally{if(h)throw k;
}}}else d.rows=[];if(b.cells){d.cells={};for(var t in this.cells)e[t]||(d.cells[t.split(".").slice(1).join(".")]=b.extended?c.cells[t]:c.cells[t].value)}return d}}]);return d}(r.Space);r.sheets={}}var q=b("./traverse.js"),n=[],f={};p.getArgs=e;c.exports=p;"undefined"!==typeof window&&(window.Hypercalc=p)}).call(this)},{"./functions/Date/index.js":3,"./functions/Geometry/index.js":5,"./functions/Math/index.js":9,"./functions/Matrix/index.js":16,"./functions/Physics/index.js":18,"./functions/Statistics/index.js":21,
"./functions/String/index.js":27,"./functions/Unit/index.js":28,"./functions/Vector/index.js":29,"./functions/add.js":30,"./functions/adda.js":31,"./functions/average.js":32,"./functions/averagea.js":33,"./functions/count.js":34,"./functions/dimensions.js":35,"./functions/divide.js":36,"./functions/dividea.js":37,"./functions/equal.js":38,"./functions/flatten.js":39,"./functions/isFunction.js":41,"./functions/isMatrix.js":42,"./functions/isNegative.js":43,"./functions/isNumber.js":44,"./functions/isPositive.js":45,
"./functions/isPrime.js":46,"./functions/isVector.js":47,"./functions/join.js":48,"./functions/multiply.js":51,"./functions/multiplya.js":52,"./functions/pow.js":53,"./functions/product.js":54,"./functions/producta.js":55,"./functions/quotient.js":56,"./functions/subtract.js":57,"./functions/subtracta.js":58,"./functions/sum.js":59,"./functions/suma.js":60,"./functions/text.js":61,"./functions/type.js":62,"./traverse.js":65}],65:[function(b,c,h){(function(){c.exports=traverse=function(b){function c(c,
d){return b.apply(this,arguments)}c.toString=function(){return b.toString()};return c}(function(b,c){for(var d=0;d<b.length;d++){var e=b[d];Array.isArray(e)?traverse(e,c):c(e,d,b)}})}).call(this)},{}]},{},[64]);
d){return b.apply(this,arguments)}c.toString=function(){return b.toString()};return c}(function(b,c){for(var d=0;d<b.length;d++){var e=b[d];Array.isArray(e)?traverse(e,c):c(e,d,b)}})}).call(this)},{}]},{},[64]);